# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import viewer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Chatroom Name')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(default='565Cu0CbEQn48FedvL0zLihL1bT9CpBMo1h', max_length=38)),
                ('is_public', models.BooleanField(default=False)),
                ('duration', models.BigIntegerField(default=2700, validators=[viewer.models.validate_duration])),
                ('joiners', models.ManyToManyField(related_name='joined_chatrooms', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_chatrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
