# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utubeu_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_video_thumb',
            field=models.TextField(blank=True, null=True, verbose_name='The thumbnail url of the last video played.'),
        ),
    ]
