# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import utubeu_viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('utubeu_viewer', '0002_chatroom_last_video_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='internal_identifier',
            field=models.CharField(default=utubeu_viewer.models.generate_id_string, max_length=38),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='identifier',
            field=models.TextField(blank=True),
        ),
    ]
