# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utubeu_viewer', '0003_auto_20161105_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
